{{- if .Values.createClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pulumi-kubernetes-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "pulumi-kubernetes-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pulumi-kubernetes-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "pulumi-kubernetes-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
